# Generated by Django 5.0.1 on 2024-01-11 10:38

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_content_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content_upload',
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
