# Generated by Django 5.0.1 on 2024-01-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_response'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='user',
            new_name='sender',
        ),
        migrations.AddField(
            model_name='response',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
