# Generated by Django 5.0.1 on 2024-01-18 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_response_accepted_datetime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='response',
            options={'ordering': ['-create_time']},
        ),
        migrations.AlterField(
            model_name='response',
            name='accepted_datetime',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
